google_domain_name = "tavusb.com"
google_project_id = "fuchi-287613"
google_bucket_name = "tavus_bucket"
deployment_environment = "tools"
credentials = "fuchicorp-service-account.json"
deployment_name = "hello-world"
deployment_endpoint = "stage"